= Dokumentationen diverser Konfigurationen                              
Sven Butzek 
Version 0.2, 16.05.2021                                             
:sectnums:                                                          
:toc:                                                               
:toclevels: 4                                                       
:toc-title: My Content                                              
                                                                    
:description: Linux commands                             
:keywords: wordpress                                                 
:imagesdir: ./img                                                   

This is my own documentation site

== Wordpress

=== Wordpress Datenbank

Datenbank liegt in /config ab, dieses Verezeichnig ist nach db_data gemounted.
Der Ordner db_restore für das zurücksichern eines SQL Dumps gedacht:

Um die Datenbank zu restaurieren genügt folgender Befehl: +
`mysql -u <user> -p <dbname> < /config/initdb.d/wordpress.sql`



=== Wordpress Debugging

in wp-config.php folgendes hinterlegen
[source,php]
----
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
@ini_set('display_errors',0);
----



== Ecodms 

=== Ecodms Backup
Im Backup Verzeichnis reicht es eine create Datei anzulegen. Dies wird von ecodms erkannt und anschließend ein Backup erstellt.
siehe script "/etc/cron.weekly/ecodmsbackup"
[source,shell]
----
#!/bin/bash

# This file will trigger ecodms to create a new backup
#touch /opt/docker/ecodms/ecoDMS/backup/create
BACKUP_PATH=/srv/backup/zeus/ecodms

touch ${BACKUP_PATH}/create

MAX_RUNTIME=$((SECONDS+3600))

while [ -f ${BACKUP_PATH}/create ]
do
      sleep 31
      if [ $SECONDS -gt $MAX_RUNTIME ]; then
              exit 1
      fi
done

echo "Backup seems to be started."

while : ; do
  FILENAME=`ls -rt ${BACKUP_PATH}/*.zip | tail -n1`
  SIZE1=`stat -c%s "$FILENAME"`
  sleep 11
  SIZE2=`stat -c%s "$FILENAME"`

  if [ "$SIZE1" -eq "$SIZE2" ]; then
    echo "no file size change detected anymore, starting copy job"
    break
  fi

  if [ $SECONDS -gt $MAX_RUNTIME ]; then
    exit 1
  fi
done

#cp "$FILENAME" /mnt/fritznas/ASMedia-asm1153e-01/backup/ecodms/backup.zip
mv -T "$FILENAME" /mnt/fritznas/ASMedia-asm1153e-01/backup/ecodms/backup.zip
----

== Linux LVM

=== Informationen zu den Volumes abrufen
[source,shell]
----
sudo lvdisplay
----

=== Logisches Volume vergrößern

==== Backup Volume vergrößern
[source,shell]
----
sudo lvextend --resizefs -L +10G /dev/data-vg/backup-lv # Größe um 10G erweitern
----

.Führt zu folgender Ausgabe
[%collapsible]
====
[source,shell]
----
Size of logical volume data-vg/backup-lv changed from 600.00 GiB (153600 extents) to 610.00 GiB (156160 extents).
Logical volume data-vg/backup-lv successfully resized.
resize2fs 1.45.5 (07-Jan-2020)
Filesystem at /dev/mapper/data--vg-backup--lv is mounted on /srv/backup; on-line resizing required
old_desc_blocks = 75, new_desc_blocks = 77
The filesystem on /dev/mapper/data--vg-backup--lv is now 159907840 (4k) blocks long.
----
====
